// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class CiclosPaquetesMantenimiento
{
    public int Id { get; set; }

    public int IdEstrategiaMantenimiento { get; set; }

    public int DuracionCiclo { get; set; }

    public string DenominacionCicloMantenimiento { get; set; }

    public string TextoCicloMantenimiento { get; set; }

    public int OrdenJerarquico { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<HistorialMantenimientoCreado> HistorialMantenimientoCreados { get; set; } = new List<HistorialMantenimientoCreado>();

    public virtual EstrategiasMantenimiento IdEstrategiaMantenimientoNavigation { get; set; }

    public virtual ICollection<PaqueteMantenimientoOperacionHojaRutum> PaqueteMantenimientoOperacionHojaRuta { get; set; } = new List<PaqueteMantenimientoOperacionHojaRutum>();
}