// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class ComponentesOrdene
{
    public int Id { get; set; }

    public int IdOrden { get; set; }

    public int IdMaterial { get; set; }

    public decimal Cantidad { get; set; }

    public decimal PrecioUnitarioActual { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Materiale IdMaterialNavigation { get; set; }

    public virtual OrdenesTrabajoEncabezado IdOrdenNavigation { get; set; }
}