// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class DocumentosMedicion
{
    public int Id { get; set; }

    public int IdPuntoMedida { get; set; }

    public DateTime FechaHoraMedicion { get; set; }

    public decimal ValorContador { get; set; }

    public decimal DiferenciaCantidad { get; set; }

    public bool Anulado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public virtual PuntosMedidum IdPuntoMedidaNavigation { get; set; }
}