// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class Equipo
{
    public int Id { get; set; }

    public string Nombreequipo { get; set; }

    public string Denominacion { get; set; }

    public int Idtipo { get; set; }

    public string Serie { get; set; }

    public DateTime? Fechaadquisicion { get; set; }

    public bool? Activo { get; set; }

    public DateTime? Puestaserviciodesde { get; set; }

    public int Idcentroemplazamiento { get; set; }

    public int Idindicadorabc { get; set; }

    public int Idusuariocreador { get; set; }

    public DateTime Fechacreacion { get; set; }

    public int? Idusuariomodificador { get; set; }

    public DateTime? Fechamodificacion { get; set; }

    public string Nombreresponsable { get; set; }

    public string Emailresponsable { get; set; }

    public int Idgrupoplanificacionmantenimiento { get; set; }

    public int Idpuestotrabajoresponsable { get; set; }

    public string NoOrdenPermanenteCombustible { get; set; }

    public string CodigoBarraUnico { get; set; }

    public bool Estadoborrado { get; set; }

    public virtual CentrosEmplazamiento IdcentroemplazamientoNavigation { get; set; }

    public virtual GruposPlanificacionMantenimiento IdgrupoplanificacionmantenimientoNavigation { get; set; }

    public virtual IndicadoresCriticidad IdindicadorabcNavigation { get; set; }

    public virtual PuestosTrabajo IdpuestotrabajoresponsableNavigation { get; set; }

    public virtual TiposEquipo IdtipoNavigation { get; set; }

    public virtual Usuario IdusuariocreadorNavigation { get; set; }

    public virtual Usuario IdusuariomodificadorNavigation { get; set; }

    public virtual ICollection<OrdenesTrabajoEncabezado> OrdenesTrabajoEncabezados { get; set; } = new List<OrdenesTrabajoEncabezado>();

    public virtual ICollection<PresupuestoEquipo> PresupuestoEquipos { get; set; } = new List<PresupuestoEquipo>();

    public virtual ICollection<PuntosMedidum> PuntosMedida { get; set; } = new List<PuntosMedidum>();
}