// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class EstrategiasMantenimiento
{
    public int Id { get; set; }

    public string NombreEstrategia { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int IdunidadEstrategia { get; set; }

    public decimal PorcHorizonteApertura { get; set; }

    public bool? EstadoBorrado { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<CiclosPaquetesMantenimiento> CiclosPaquetesMantenimientos { get; set; } = new List<CiclosPaquetesMantenimiento>();

    public virtual UnidadesMedidaCaracteristica IdunidadEstrategiaNavigation { get; set; }

    public virtual ICollection<PaquetesMantenimiento> PaquetesMantenimientos { get; set; } = new List<PaquetesMantenimiento>();
}