// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class GruposHojasRutum
{
    public int Id { get; set; }

    public string NombregrupoHojaRuta { get; set; }

    public int ContadorGrupoHojaRuta { get; set; }

    public int IdCentroEmplazamiento { get; set; }

    public int IdPuestoTrabajo { get; set; }

    public int IdgrupoPlanificacion { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public bool IdestrategiaMantenimiento { get; set; }

    public virtual ICollection<OperacionesHojasRutum> OperacionesHojasRuta { get; set; } = new List<OperacionesHojasRutum>();

    public virtual ICollection<PaquetesMantenimiento> PaquetesMantenimientos { get; set; } = new List<PaquetesMantenimiento>();
}