// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class HistorialMantenimientoCreado
{
    public int Id { get; set; }

    public int IdCicloPaqueteMantenimiento { get; set; }

    public int IdPuntoMedidaAsociado { get; set; }

    public int IdOrdenMantenimientoCreada { get; set; }

    public decimal LecturaContadorEjecucion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual CiclosPaquetesMantenimiento IdCicloPaqueteMantenimientoNavigation { get; set; }

    public virtual OrdenesTrabajoEncabezado IdOrdenMantenimientoCreadaNavigation { get; set; }

    public virtual PuntosMedidum IdPuntoMedidaAsociadoNavigation { get; set; }
}