// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class Materiale
{
    public int Id { get; set; }

    public string CodigoMaterial { get; set; }

    public int IdUnidadMedida { get; set; }

    public string DescripcionMaterial { get; set; }

    public int IdCategoriaMaterial { get; set; }

    public bool? Activo { get; set; }

    public decimal StockInicial { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public decimal? PrecioUnitarioMonedaLocal { get; set; }

    public int IdSeccionMaquina { get; set; }

    public virtual ICollection<ComponentesOperacionHojaRutum> ComponentesOperacionHojaRuta { get; set; } = new List<ComponentesOperacionHojaRutum>();

    public virtual ICollection<ComponentesOrdene> ComponentesOrdenes { get; set; } = new List<ComponentesOrdene>();

    public virtual CategoriasMateriale IdCategoriaMaterialNavigation { get; set; }

    public virtual SeccionesMaquina IdSeccionMaquinaNavigation { get; set; }

    public virtual UnidadesMedidaCaracteristica IdUnidadMedidaNavigation { get; set; }
}