// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class OperacionesHojasRutum
{
    public int Id { get; set; }

    public int IdGrupoHojaRuta { get; set; }

    public int NumeroOperacion { get; set; }

    public int IdCentroEmplazamiento { get; set; }

    public string DescripcionOperacion { get; set; }

    public decimal CantidadTrabajo { get; set; }

    public int IdunidadMedidaTrabajo { get; set; }

    public decimal CantidadHombres { get; set; }

    public decimal DuracionPorHombre { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<ComponentesOperacionHojaRutum> ComponentesOperacionHojaRuta { get; set; } = new List<ComponentesOperacionHojaRutum>();

    public virtual GruposHojasRutum IdGrupoHojaRutaNavigation { get; set; }

    public virtual ICollection<PaqueteMantenimientoOperacionHojaRutum> PaqueteMantenimientoOperacionHojaRuta { get; set; } = new List<PaqueteMantenimientoOperacionHojaRutum>();
}