// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class PaqueteMantenimientoOperacionHojaRutum
{
    public int Id { get; set; }

    public int IdOperacionHoraRuta { get; set; }

    public int IdCicloPaqueteMantenimiento { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual CiclosPaquetesMantenimiento IdCicloPaqueteMantenimientoNavigation { get; set; }

    public virtual OperacionesHojasRutum IdOperacionHoraRutaNavigation { get; set; }
}