// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class PaquetesMantenimiento
{
    public int Id { get; set; }

    public string PlanMantPreventivo { get; set; }

    public int IdEstrategiaMantenimiento { get; set; }

    public int IdPuntoMedida { get; set; }

    public int IdCentroEmplazamiento { get; set; }

    public int IdClaseOrden { get; set; }

    public int IdPuestoTrabajoResp { get; set; }

    public int IdgrupoHojaRuta { get; set; }

    public int Idequiporeferencia { get; set; }

    public decimal PorcHorizonteApertura { get; set; }

    public decimal ValorInicialContador { get; set; }

    public int IdPrioridadManto { get; set; }

    public int IdgrupoPlanificacion { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ClasesdeOrden IdClaseOrdenNavigation { get; set; }

    public virtual EstrategiasMantenimiento IdEstrategiaMantenimientoNavigation { get; set; }

    public virtual PrioridadesMantenimientos IdPrioridadMantoNavigation { get; set; }

    public virtual PuntosMedidum IdPuntoMedidaNavigation { get; set; }

    public virtual GruposHojasRutum IdgrupoHojaRutaNavigation { get; set; }
}