// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class PresupuestoEquipo
{
    public int Id { get; set; }

    public int IdEquipo { get; set; }

    public decimal HorasKmPlan { get; set; }

    public int IdPeriodo { get; set; }

    public decimal ValorGastoPlanMonedaLocal { get; set; }

    public string TextoBreve { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Equipo IdEquipoNavigation { get; set; }

    public virtual Periodo IdPeriodoNavigation { get; set; }
}