// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FLAGSOLUTIOSAPI.Models;

public partial class PuntosMedidum
{
    [Key]
    public int Id { get; set; }

    public int IdTipoPuntoMedida { get; set; }

    public int IdEquipo { get; set; }

    public string Denominacion { get; set; }

    public int IdUnidadCaracteristica { get; set; }

    public decimal ContadorIniciaDesde { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public decimal ContadorrotaAlos { get; set; }

    public virtual ICollection<DocumentosMedicion> DocumentosMedicions { get; set; } = new List<DocumentosMedicion>();

    public virtual ICollection<HistorialMantenimientoCreado> HistorialMantenimientoCreados { get; set; } = new List<HistorialMantenimientoCreado>();

    public virtual Equipo IdEquipoNavigation { get; set; }

    public virtual TiposPuntoMedida IdTipoPuntoMedidaNavigation { get; set; }

    public virtual UnidadesMedidaCaracteristica IdUnidadCaracteristicaNavigation { get; set; }

    public virtual ICollection<PaquetesMantenimiento> PaquetesMantenimientos { get; set; } = new List<PaquetesMantenimiento>();
}