// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FLAGSOLUTIOSAPI.Models;

public partial class Sucursale
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int EmpresaId { get; set; }

    public DateTime Creacion { get; set; }

    public bool Activo { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}