// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FLAGSOLUTIOSAPI.Models;

public partial class TiposEquipo
{
    [Key]
    public int Id { get; set; }

    public string Nombretipo { get; set; }

    public int Idusuariocreador { get; set; }

    public DateTime Fechacreacion { get; set; }

    public int? Idusuariomodificador { get; set; }

    public DateTime? Fechamodificacion { get; set; }

    public bool? Activo { get; set; }

    public bool Estadoborrado { get; set; }

    public virtual ICollection<Equipo> Equipos { get; set; } = new List<Equipo>();
}