// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FLAGSOLUTIOSAPI.Models;

public partial class UnidadesMedidaCaracteristica
{

    [Key]
    public int Id { get; set; }

    public string NombreUm { get; set; }

    public string TextoUnidadMedida { get; set; }

    public bool? Activo { get; set; }

    public bool? EstadoBorrado { get; set; }

    public int IdUsuarioCreador { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int? IdUsuarioModificador { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<EstrategiasMantenimiento> EstrategiasMantenimientos { get; set; } = new List<EstrategiasMantenimiento>();

    public virtual ICollection<Materiale> Materiales { get; set; } = new List<Materiale>();

    public virtual ICollection<PuntosMedidum> PuntosMedida { get; set; } = new List<PuntosMedidum>();
}