// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FLAGSOLUTIOSAPI.Models;

public partial class UsuariosMenu
{
    [Key]
    public int Id { get; set; }

    public int UsuarioId { get; set; }

    public int MenuId { get; set; }

    public DateTime Creacion { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Usuario Usuario { get; set; }
}